x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  restart: unless-stopped
  networks:
    - collabberry-backend

services:
  backend:
    <<: *common
    container_name: backend
    build: .
    environment:
      JWT_SECRET: secret
      INVITATION_URL: "http://localhost:3000/invitation"
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_PASS: password
      DB_NAME: collabberry
      DB_UNAME: root
      ARBITRUM_RPC_URL: https://arb1.arbitrum.io/rpc
      ARBITRUM_SEPOLIA_RPC_URL: https://api.zan.top/arb-sepolia
      CELO_RPC_URL: https://forno.celo.org
    ports:
      - 3000:3000
    depends_on:
      - mysql

  scheduled-jobs:
    <<: *common
    container_name: scheduled-jobs
    build: .
    environment:
      ROUNDS_START_GENERATION_SCHEDULE: "* * * * *"
      COMPLETE_ROUNDS_SCHEDULE: "* * * * *"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_PASS: password
      DB_NAME: collabberry
      DB_UNAME: root
    command: ["node", "/app/dist/src/roundsStartJob.index.js"]
    depends_on:
      - mysql

  mysql:
    <<: *common
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collabberry
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  collabberry-backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
