x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  restart: unless-stopped
  networks:
    - collabberry-backend

services:
  backend:
    <<: *common
    container_name: backend
    build: .
    environment:
      JWT_SECRET: secret
      INVITATION_URL: "http://localhost:3000/invitation"
      PORT: 3000
      DATABASE_URL: mysql://root:password@mysql:3306/collabberry # Updated for MySQL
    ports:
      - 80:3000
    depends_on:
      - mysql

  mysql:
    <<: *common
    container_name: mysql
    image: mysql:latest
    environment:
      DATABASE_URL: mysql://root:password@localhost:3306/collabberry?allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collabberry
      DB_HOST: localhost
      DB_PORT: 3306
      DB_PASS: password
      DB_NAME: collabberry
      DB_UNAME: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  collabberry-backend:
    driver: bridge
