x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  restart: unless-stopped
  networks:
    - collabberry-backend

services:
  backend:
    <<: *common
    container_name: backend
    build: .
    environment:
      JWT_SECRET: secret
      INVITATION_URL: "http://localhost:3000/invitation"
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - mongo

networks:
  collabberry-backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
