x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  env_file:
    - .compose.secrets.env
  restart: unless-stopped
  networks:
    - collabberry-backend

services:
  backend:
    <<: *common
    container_name: backend
    build: .
    image: collabberry/backend-app:latest
    environment:
      JWT_SECRET: secret
      INVITATION_URL: "http://localhost:3000/invitation"
      PORT: 3000
    ports:
      - 80:3000
    depends_on:
      - mysql

networks:
  collabberry-backend:
    driver: bridge
